
/**
 * skillTaxonomy.ts
 *
 * OptioHire — Master Skill Taxonomy (100 Professional Categories)
 *
 * This file is intentionally NOT injected into the LLM prompt in full.
 * It lives in Node.js memory and is queried by the JIT Taxonomy Router
 * (getRelevantTaxonomyCategories) at runtime, which selects only the
 * 2-4 most relevant categories for a given job posting before
 * constructing the AI prompt. See ai-scoring.ts for the consumer.
 *
 * Each category has:
 *  - id: stable machine key (snake_case)
 *  - label: human-readable name
 *  - keywords: title/skill tokens used by the router for fast matching
 *  - skills: 8-10 representative hard/domain skills the AI checks
 *            candidate CVs against for that profession
 *
 * UNIVERSAL_SOFT_SKILLS is a separate add-on layer, always available to
 * the router to optionally append regardless of which category(ies)
 * matched — it is NOT one of the 100 numbered categories.
 */

export interface TaxonomyCategory {
    id: string;
    label: string;
    group: string;
    keywords: string[];
    skills: string[];
}

/* ------------------------------------------------------------------ */
/* UNIVERSAL ADD-ON LAYER (not counted in the 100)                    */
/* ------------------------------------------------------------------ */

export const UNIVERSAL_SOFT_SKILLS: TaxonomyCategory = {
    id: "universal_soft_skills",
    label: "Leadership & Soft Skills",
    group: "Universal",
    keywords: [], // always eligible for injection, never matched directly
    skills: [
        "Communication",
        "Leadership",
        "Stakeholder Management",
        "Problem Solving",
        "Collaboration & Teamwork",
        "Time Management",
        "Adaptability",
        "Conflict Resolution",
        "Decision Making",
        "Mentorship & Coaching",
    ],
};

/* ------------------------------------------------------------------ */
/* THE 100 PROFESSIONAL CATEGORIES                                    */
/* ------------------------------------------------------------------ */

export const SKILL_TAXONOMY: TaxonomyCategory[] = [
    /* ============================== SOFTWARE & IT ============================== */
    {
        id: "frontend_engineering",
        label: "Frontend Engineering",
        group: "Software & IT",
        keywords: ["frontend", "front-end", "react", "vue", "angular", "ui engineer", "javascript developer"],
        skills: [
            "JavaScript/TypeScript",
            "React/Vue/Angular",
            "HTML5 & CSS3",
            "Responsive Design",
            "State Management (Redux/Zustand)",
            "Web Performance Optimization",
            "Accessibility (WCAG)",
            "REST/GraphQL Integration",
            "Component Architecture",
            "Browser DevTools Debugging",
        ],
    },
    {
        id: "backend_api_engineering",
        label: "Backend & API Engineering",
        group: "Software & IT",
        keywords: ["backend", "back-end", "api", "node", "django", "spring", "server-side"],
        skills: [
            "Server-Side Languages (Node/Python/Java/Go)",
            "REST/GraphQL API Design",
            "Database Design & ORM",
            "Authentication & Authorization",
            "Microservices Architecture",
            "Caching Strategies (Redis)",
            "Message Queues (Kafka/RabbitMQ)",
            "API Security",
            "Unit & Integration Testing",
            "System Scalability",
        ],
    },
    {
        id: "full_stack_development",
        label: "Full-Stack Development",
        group: "Software & IT",
        keywords: ["full stack", "full-stack", "fullstack developer", "mern", "mean"],
        skills: [
            "Frontend Frameworks (React/Vue)",
            "Backend Frameworks (Node/Express/Django)",
            "Database Management (SQL/NoSQL)",
            "API Design & Integration",
            "Version Control (Git)",
            "CI/CD Pipelines",
            "Cloud Deployment",
            "Authentication Systems",
            "Testing (Unit/E2E)",
            "Architecture Decisions",
        ],
    },
    {
        id: "mobile_app_development",
        label: "Mobile App Development (iOS/Android)",
        group: "Software & IT",
        keywords: ["ios", "android", "swift", "kotlin", "react native", "flutter", "mobile developer"],
        skills: [
            "Swift/Kotlin/Java",
            "React Native/Flutter",
            "Mobile UI/UX Guidelines",
            "App Store/Play Store Deployment",
            "Push Notifications",
            "Offline Data Sync",
            "Mobile Performance Tuning",
            "Native API Integration",
            "Crash Reporting & Analytics",
            "Cross-Platform Architecture",
        ],
    },
    {
        id: "devops_sre",
        label: "DevOps & SRE (Site Reliability Engineering)",
        group: "Software & IT",
        keywords: ["devops", "sre", "site reliability", "infrastructure engineer", "platform engineer"],
        skills: [
            "CI/CD Pipeline Design",
            "Docker & Kubernetes",
            "Infrastructure as Code (Terraform)",
            "Monitoring & Observability (Prometheus/Grafana)",
            "Incident Response & On-Call",
            "Cloud Platforms (AWS/GCP/Azure)",
            "Configuration Management (Ansible)",
            "Scripting (Bash/Python)",
            "SLA/SLO Management",
            "Disaster Recovery Planning",
        ],
    },
    {
        id: "cloud_architecture",
        label: "Cloud Architecture & Infrastructure",
        group: "Software & IT",
        keywords: ["cloud architect", "aws", "azure", "gcp", "cloud engineer", "solutions architect"],
        skills: [
            "AWS/Azure/GCP Core Services",
            "Cloud Network Design",
            "Cost Optimization (FinOps)",
            "Multi-Cloud/Hybrid Architecture",
            "Identity & Access Management",
            "Serverless Architecture",
            "Infrastructure as Code",
            "High Availability Design",
            "Cloud Security Best Practices",
            "Migration Planning",
        ],
    },
    {
        id: "cyber_security",
        label: "Cyber Security & Information Security",
        group: "Software & IT",
        keywords: ["cyber security", "infosec", "security analyst", "penetration tester", "soc analyst"],
        skills: [
            "Threat Detection & Analysis",
            "Penetration Testing",
            "SIEM Tools (Splunk/Sentinel)",
            "Vulnerability Management",
            "Network Security",
            "Incident Response",
            "Security Compliance (ISO 27001/SOC2)",
            "Identity & Access Management",
            "Cryptography Fundamentals",
            "Risk Assessment",
        ],
    },
    {
        id: "qa_automation_testing",
        label: "Quality Assurance (QA) & Automation Testing",
        group: "Software & IT",
        keywords: ["qa engineer", "test engineer", "automation tester", "sdet", "quality assurance"],
        skills: [
            "Test Case Design",
            "Automated Testing Frameworks (Selenium/Cypress)",
            "API Testing (Postman)",
            "Regression Testing",
            "Performance/Load Testing",
            "Bug Tracking & Reporting",
            "CI/CD Test Integration",
            "Manual & Exploratory Testing",
            "Test Plan Documentation",
            "Cross-Browser/Device Testing",
        ],
    },
    {
        id: "database_administration",
        label: "Database Administration (DBA)",
        group: "Software & IT",
        keywords: ["dba", "database administrator", "sql server admin", "oracle dba"],
        skills: [
            "SQL & Query Optimization",
            "Database Backup & Recovery",
            "Replication & Clustering",
            "Performance Tuning",
            "Database Security",
            "PostgreSQL/MySQL/Oracle Administration",
            "Capacity Planning",
            "High Availability Setup",
            "Data Migration",
            "Monitoring & Alerting",
        ],
    },
    {
        id: "it_support_helpdesk",
        label: "IT Support & Helpdesk",
        group: "Software & IT",
        keywords: ["it support", "helpdesk", "desktop support", "technical support", "service desk"],
        skills: [
            "Troubleshooting (Hardware/Software)",
            "Ticketing Systems (Zendesk/ServiceNow)",
            "Active Directory Administration",
            "Remote Support Tools",
            "Operating Systems (Windows/macOS/Linux)",
            "Network Basics",
            "Customer Service",
            "Asset Management",
            "Basic Scripting",
            "SLA Compliance",
        ],
    },
    {
        id: "network_engineering",
        label: "Network Engineering & Administration",
        group: "Software & IT",
        keywords: ["network engineer", "network administrator", "ccna", "ccnp", "network architect"],
        skills: [
            "Routing & Switching (Cisco/Juniper)",
            "TCP/IP & Subnetting",
            "Firewall Configuration",
            "VPN Setup & Management",
            "Network Monitoring Tools",
            "Wireless Network Design",
            "Network Security",
            "Load Balancing",
            "SD-WAN",
            "Network Troubleshooting",
        ],
    },

    /* ========================= DATA & ARTIFICIAL INTELLIGENCE ========================= */
    {
        id: "data_science_ml",
        label: "Data Science & Machine Learning",
        group: "Data & AI",
        keywords: ["data scientist", "machine learning engineer", "ml engineer", "predictive modeling"],
        skills: [
            "Python/R for Data Science",
            "Machine Learning Algorithms",
            "Statistical Modeling",
            "Feature Engineering",
            "Model Evaluation & Validation",
            "scikit-learn/TensorFlow/PyTorch",
            "Data Visualization",
            "A/B Testing",
            "SQL for Data Analysis",
            "MLOps Fundamentals",
        ],
    },
    {
        id: "ai_engineering_llm",
        label: "Artificial Intelligence Engineering (LLMs/GenAI)",
        group: "Data & AI",
        keywords: ["ai engineer", "llm", "genai", "generative ai", "prompt engineer", "nlp engineer"],
        skills: [
            "LLM Integration (OpenAI/Anthropic/Groq)",
            "Prompt Engineering",
            "Retrieval-Augmented Generation (RAG)",
            "Vector Databases (pgvector/Pinecone)",
            "Fine-Tuning & Embeddings",
            "AI Agent Orchestration",
            "Token/Cost Optimization",
            "Model Evaluation & Guardrails",
            "Python (LangChain/Vercel AI SDK)",
            "AI Safety & Hallucination Mitigation",
        ],
    },
    {
        id: "data_engineering_pipelines",
        label: "Data Engineering & Pipelines",
        group: "Data & AI",
        keywords: ["data engineer", "etl", "data pipeline", "data platform engineer"],
        skills: [
            "ETL/ELT Pipeline Design",
            "Apache Spark/Airflow",
            "Data Warehousing (Snowflake/BigQuery)",
            "SQL & Query Optimization",
            "Data Modeling",
            "Streaming Data (Kafka)",
            "Python/Scala for Data Engineering",
            "Data Quality & Validation",
            "Cloud Data Platforms",
            "Workflow Orchestration",
        ],
    },
    {
        id: "bi_data_analytics",
        label: "Business Intelligence (BI) & Data Analytics",
        group: "Data & AI",
        keywords: ["business intelligence", "data analyst", "bi analyst", "reporting analyst"],
        skills: [
            "SQL Query Writing",
            "Power BI/Tableau",
            "Data Modeling & Dashboards",
            "Excel Advanced Functions",
            "KPI & Metrics Design",
            "Data Storytelling",
            "ETL Basics",
            "Statistical Analysis",
            "Stakeholder Reporting",
            "Data Governance",
        ],
    },
    {
        id: "quantitative_analysis",
        label: "Quantitative Analysis",
        group: "Data & AI",
        keywords: ["quant", "quantitative analyst", "quant researcher", "algo trading"],
        skills: [
            "Statistical & Mathematical Modeling",
            "Python/R/MATLAB",
            "Financial Derivatives Pricing",
            "Time Series Analysis",
            "Risk Modeling",
            "Algorithmic Trading Strategies",
            "Monte Carlo Simulation",
            "Stochastic Calculus",
            "Backtesting Frameworks",
            "Data Analysis at Scale",
        ],
    },

    /* ============================== PRODUCT & DESIGN ============================== */
    {
        id: "product_management",
        label: "Product Management",
        group: "Product & Design",
        keywords: ["product manager", "product owner", "pm", "product lead"],
        skills: [
            "Product Roadmapping",
            "User Research & Discovery",
            "Backlog Prioritization",
            "A/B Testing & Experimentation",
            "Stakeholder Management",
            "Agile/Scrum Methodology",
            "Product Analytics",
            "Go-To-Market Strategy",
            "Wireframing/Spec Writing",
            "Cross-Functional Leadership",
        ],
    },
    {
        id: "ui_ux_design",
        label: "UI/UX Design & Research",
        group: "Product & Design",
        keywords: ["ui designer", "ux designer", "product designer", "ux researcher"],
        skills: [
            "User Research & Usability Testing",
            "Wireframing & Prototyping (Figma)",
            "Interaction Design",
            "Information Architecture",
            "Design Systems",
            "Visual/UI Design",
            "Accessibility Standards",
            "User Journey Mapping",
            "Design Critique & Iteration",
            "Cross-Platform Design",
        ],
    },
    {
        id: "graphic_design_illustration",
        label: "Graphic Design & Illustration",
        group: "Product & Design",
        keywords: ["graphic designer", "illustrator", "visual designer", "brand designer"],
        skills: [
            "Adobe Creative Suite (Photoshop/Illustrator)",
            "Typography",
            "Layout & Composition",
            "Brand Identity Design",
            "Print & Digital Design",
            "Color Theory",
            "Illustration Techniques",
            "Packaging Design",
            "Vector Graphics",
            "Client Presentation",
        ],
    },
    {
        id: "industrial_product_design",
        label: "Industrial & Product Design",
        group: "Product & Design",
        keywords: ["industrial designer", "product designer (physical)", "cad designer"],
        skills: [
            "CAD Software (SolidWorks/Rhino)",
            "Prototyping & Model Making",
            "Materials & Manufacturing Processes",
            "Ergonomics & Human Factors",
            "Sketching & Ideation",
            "Design for Manufacturing (DFM)",
            "3D Printing/Rapid Prototyping",
            "User-Centered Design",
            "Sustainability in Design",
            "Technical Drawings",
        ],
    },
    {
        id: "3d_animation_motion_graphics",
        label: "3D Animation & Motion Graphics",
        group: "Product & Design",
        keywords: ["3d animator", "motion graphics designer", "vfx artist", "animator"],
        skills: [
            "Maya/Blender/Cinema 4D",
            "After Effects",
            "Character Rigging & Animation",
            "Storyboarding",
            "Compositing & VFX",
            "Texturing & Lighting",
            "Motion Design Principles",
            "Video Editing",
            "Rendering Pipelines",
            "Visual Storytelling",
        ],
    },
    {
        id: "game_design_development",
        label: "Game Design & Development",
        group: "Product & Design",
        keywords: ["game designer", "game developer", "unity developer", "unreal developer"],
        skills: [
            "Unity/Unreal Engine",
            "C#/C++ Game Programming",
            "Game Mechanics Design",
            "Level Design",
            "Game Physics",
            "Multiplayer/Networking Systems",
            "3D/2D Asset Integration",
            "Playtesting & Balancing",
            "Narrative/Systems Design",
            "Performance Optimization",
        ],
    },

    /* ===================== SALES, MARKETING & COMMUNICATIONS ===================== */
    {
        id: "b2b_sales",
        label: "B2B Sales & Account Executives",
        group: "Sales, Marketing & Comms",
        keywords: ["b2b sales", "account executive", "sales executive", "enterprise sales"],
        skills: [
            "Pipeline Management (CRM)",
            "Solution Selling",
            "Lead Qualification",
            "Negotiation & Closing",
            "Account Planning",
            "Cold Outreach & Prospecting",
            "Sales Forecasting",
            "Objection Handling",
            "Contract Negotiation",
            "Relationship Building",
        ],
    },
    {
        id: "customer_success",
        label: "Customer Success & Account Management",
        group: "Sales, Marketing & Comms",
        keywords: ["customer success manager", "account manager", "client success"],
        skills: [
            "Onboarding & Adoption Strategy",
            "Churn Prevention & Retention",
            "Upsell/Cross-Sell Strategy",
            "Account Health Monitoring",
            "Customer Relationship Management",
            "QBR (Quarterly Business Review) Delivery",
            "Customer Advocacy",
            "Renewal Management",
            "Cross-Functional Escalation Handling",
            "Customer Health Metrics (NPS/CSAT)",
        ],
    },
    {
        id: "digital_marketing_seo_sem",
        label: "Digital Marketing, SEO & SEM",
        group: "Sales, Marketing & Comms",
        keywords: ["digital marketer", "seo specialist", "sem specialist", "growth marketer", "ppc"],
        skills: [
            "SEO (On-Page/Off-Page/Technical)",
            "SEM/PPC Campaign Management (Google Ads)",
            "Google Analytics/GA4",
            "Conversion Rate Optimization",
            "Keyword Research",
            "Marketing Automation Tools",
            "Email Marketing Campaigns",
            "A/B Testing",
            "Content Marketing Strategy",
            "Paid Social Advertising",
        ],
    },
    {
        id: "content_creation_copywriting",
        label: "Content Creation & Copywriting",
        group: "Sales, Marketing & Comms",
        keywords: ["copywriter", "content writer", "content creator", "content strategist"],
        skills: [
            "Copywriting & Persuasive Writing",
            "SEO Content Writing",
            "Content Strategy & Calendars",
            "Brand Voice & Tone",
            "Editing & Proofreading",
            "Storytelling",
            "Blog/Article Writing",
            "Email Copywriting",
            "Research & Fact-Checking",
            "Content Performance Analysis",
        ],
    },
    {
        id: "social_media_community",
        label: "Social Media & Community Management",
        group: "Sales, Marketing & Comms",
        keywords: ["social media manager", "community manager", "social media strategist"],
        skills: [
            "Social Media Strategy",
            "Content Calendar Management",
            "Community Engagement & Moderation",
            "Platform-Specific Best Practices",
            "Social Listening Tools",
            "Influencer Collaboration",
            "Paid Social Campaigns",
            "Analytics & Reporting",
            "Crisis Management (Social)",
            "Brand Voice Consistency",
        ],
    },
    {
        id: "public_relations_comms",
        label: "Public Relations (PR) & Corporate Comms",
        group: "Sales, Marketing & Comms",
        keywords: ["pr manager", "public relations", "corporate communications", "press officer"],
        skills: [
            "Press Release Writing",
            "Media Relations & Pitching",
            "Crisis Communications",
            "Stakeholder Messaging",
            "Reputation Management",
            "Spokesperson Coordination",
            "Internal Communications",
            "Event/Press Conference Coordination",
            "Media Monitoring",
            "Brand Narrative Development",
        ],
    },
    {
        id: "event_planning_coordination",
        label: "Event Planning & Coordination",
        group: "Sales, Marketing & Comms",
        keywords: ["event planner", "event coordinator", "event manager"],
        skills: [
            "Event Logistics Planning",
            "Vendor & Venue Negotiation",
            "Budget Management",
            "Timeline & Run-of-Show Creation",
            "On-Site Event Coordination",
            "Stakeholder Communication",
            "Risk & Contingency Planning",
            "Registration/Ticketing Systems",
            "Sponsorship Coordination",
            "Post-Event Evaluation",
        ],
    },
    {
        id: "brand_management",
        label: "Brand Management",
        group: "Sales, Marketing & Comms",
        keywords: ["brand manager", "brand strategist"],
        skills: [
            "Brand Strategy Development",
            "Market & Competitor Research",
            "Brand Positioning & Messaging",
            "Campaign Planning",
            "Brand Guidelines Management",
            "Consumer Insights Analysis",
            "Cross-Functional Brand Alignment",
            "Budget & P&L Management",
            "Product Launch Strategy",
            "Brand Performance Tracking",
        ],
    },

    /* ===================== BUSINESS, STRATEGY & OPERATIONS ===================== */
    {
        id: "operations_management_coo",
        label: "Operations Management & COO",
        group: "Business, Strategy & Ops",
        keywords: ["operations manager", "coo", "head of operations"],
        skills: [
            "Process Optimization",
            "Cross-Functional Leadership",
            "Budgeting & Resource Allocation",
            "KPI Development & Tracking",
            "Vendor & Stakeholder Management",
            "Organizational Design",
            "Operational Risk Management",
            "Change Management",
            "Strategic Planning",
            "Performance Reporting",
        ],
    },
    {
        id: "project_management_scrum",
        label: "Project Management (PMP) & Scrum Master",
        group: "Business, Strategy & Ops",
        keywords: ["project manager", "scrum master", "pmp", "agile coach"],
        skills: [
            "Agile/Scrum Methodology",
            "Project Planning & Scheduling",
            "Risk & Issue Management",
            "Stakeholder Communication",
            "Budget Management",
            "Resource Allocation",
            "Sprint Planning & Retrospectives",
            "Jira/Asana/MS Project",
            "Scope Management",
            "Team Facilitation",
        ],
    },
    {
        id: "business_strategy_consulting",
        label: "Business Strategy & Management Consulting",
        group: "Business, Strategy & Ops",
        keywords: ["management consultant", "strategy consultant", "business strategist"],
        skills: [
            "Market & Competitive Analysis",
            "Financial Modeling",
            "Strategic Planning Frameworks",
            "Stakeholder Interviewing",
            "Business Case Development",
            "Data-Driven Recommendations",
            "Presentation & Storyboarding",
            "Change Management",
            "Operating Model Design",
            "Client Relationship Management",
        ],
    },
    {
        id: "supply_chain_logistics",
        label: "Supply Chain Management & Logistics",
        group: "Business, Strategy & Ops",
        keywords: ["supply chain manager", "logistics manager", "supply chain analyst"],
        skills: [
            "Demand Planning & Forecasting",
            "Inventory Management",
            "Logistics & Distribution Planning",
            "Supplier Relationship Management",
            "ERP Systems (SAP/Oracle)",
            "Warehouse Management",
            "Freight & Transportation Coordination",
            "Supply Chain Risk Management",
            "Lean/Six Sigma Principles",
            "Cost Reduction Initiatives",
        ],
    },
    {
        id: "procurement_sourcing",
        label: "Procurement & Strategic Sourcing",
        group: "Business, Strategy & Ops",
        keywords: ["procurement manager", "sourcing manager", "purchasing manager", "buyer"],
        skills: [
            "Vendor Negotiation",
            "Strategic Sourcing",
            "Contract Management",
            "Supplier Performance Evaluation",
            "Cost Analysis & Reduction",
            "RFP/RFQ Management",
            "Procurement Software (Ariba/Coupa)",
            "Risk & Compliance in Sourcing",
            "Category Management",
            "Total Cost of Ownership Analysis",
        ],
    },
    {
        id: "customer_support_ops",
        label: "Customer Support & Service Operations",
        group: "Business, Strategy & Ops",
        keywords: ["customer support", "customer service representative", "support specialist"],
        skills: [
            "Ticketing/Helpdesk Tools (Zendesk)",
            "Customer Communication Skills",
            "Conflict De-escalation",
            "Product/Service Knowledge",
            "SLA Compliance",
            "Multi-Channel Support (Chat/Email/Phone)",
            "Customer Feedback Analysis",
            "Process Documentation",
            "Escalation Management",
            "CSAT/NPS Improvement",
        ],
    },
    {
        id: "risk_management_compliance",
        label: "Risk Management & Compliance",
        group: "Business, Strategy & Ops",
        keywords: ["risk manager", "compliance officer", "compliance analyst", "grc"],
        skills: [
            "Regulatory Compliance Frameworks",
            "Risk Assessment & Mitigation",
            "Internal Controls Design",
            "Audit Coordination",
            "Policy Development",
            "AML/KYC (where applicable)",
            "Compliance Reporting",
            "Incident Investigation",
            "Governance Frameworks",
            "Training & Awareness Programs",
        ],
    },
    {
        id: "real_estate_property_mgmt",
        label: "Real Estate & Property Management",
        group: "Business, Strategy & Ops",
        keywords: ["real estate agent", "property manager", "leasing manager", "realtor"],
        skills: [
            "Property Valuation",
            "Lease Negotiation",
            "Tenant Relationship Management",
            "Property Maintenance Coordination",
            "Market Analysis",
            "Real Estate Law Basics",
            "Listing & Marketing Properties",
            "Facilities Management",
            "Rent Collection & Budgeting",
            "Client/Investor Reporting",
        ],
    },

    /* ===================== HUMAN RESOURCES & ADMINISTRATION ===================== */
    {
        id: "hr_business_partner",
        label: "HR Business Partner & Generalist",
        group: "HR & Admin",
        keywords: ["hr business partner", "hr generalist", "hr manager"],
        skills: [
            "Employee Relations",
            "HR Policy Development",
            "Performance Management Systems",
            "Workforce Planning",
            "HRIS Systems",
            "Labor Law Compliance",
            "Organizational Development",
            "Conflict Resolution",
            "Onboarding/Offboarding Processes",
            "Stakeholder Consulting",
        ],
    },
    {
        id: "talent_acquisition_recruiting",
        label: "Talent Acquisition & Recruiting",
        group: "HR & Admin",
        keywords: ["recruiter", "talent acquisition", "technical recruiter", "sourcer"],
        skills: [
            "Sourcing Strategies (Boolean/LinkedIn)",
            "Applicant Tracking Systems (ATS)",
            "Candidate Screening & Interviewing",
            "Employer Branding",
            "Pipeline Management",
            "Offer Negotiation",
            "Diversity Hiring Practices",
            "Job Description Writing",
            "Stakeholder/Hiring Manager Partnership",
            "Recruitment Metrics & Reporting",
        ],
    },
    {
        id: "compensation_benefits",
        label: "Compensation, Benefits & Rewards",
        group: "HR & Admin",
        keywords: ["compensation analyst", "benefits manager", "total rewards", "comp & ben"],
        skills: [
            "Salary Benchmarking",
            "Compensation Structure Design",
            "Benefits Administration",
            "Pay Equity Analysis",
            "Incentive/Bonus Program Design",
            "HRIS & Payroll Systems",
            "Regulatory Compliance (Compensation)",
            "Job Evaluation & Leveling",
            "Total Rewards Strategy",
            "Market Survey Analysis",
        ],
    },
    {
        id: "employee_relations_culture",
        label: "Employee Relations & Culture",
        group: "HR & Admin",
        keywords: ["employee relations", "culture manager", "people experience"],
        skills: [
            "Conflict Mediation",
            "Investigations & Grievance Handling",
            "Culture & Engagement Programs",
            "Policy Interpretation",
            "Employee Engagement Surveys",
            "DEI Initiatives",
            "Labor Relations",
            "Performance Improvement Plans",
            "Workplace Investigations",
            "Change Communication",
        ],
    },
    {
        id: "executive_admin_assistance",
        label: "Executive & Administrative Assistance",
        group: "HR & Admin",
        keywords: ["executive assistant", "administrative assistant", "office manager", "ea"],
        skills: [
            "Calendar & Scheduling Management",
            "Travel Coordination",
            "Document Preparation",
            "Meeting/Board Prep & Minutes",
            "Office Administration",
            "Confidentiality & Discretion",
            "Expense Management",
            "Vendor Coordination",
            "Communication on Behalf of Executives",
            "Multi-Priority Task Management",
        ],
    },

    /* ===================== FINANCE, ACCOUNTING & LEGAL ===================== */
    {
        id: "financial_analysis_fpa",
        label: "Financial Analysis (FP&A)",
        group: "Finance, Accounting & Legal",
        keywords: ["fp&a", "financial analyst", "finance analyst"],
        skills: [
            "Financial Modeling",
            "Budgeting & Forecasting",
            "Variance Analysis",
            "Excel Advanced Modeling",
            "Financial Reporting",
            "Scenario/Sensitivity Analysis",
            "KPI Dashboarding",
            "ERP Systems (SAP/Oracle/NetSuite)",
            "Cash Flow Analysis",
            "Business Partnering",
        ],
    },
    {
        id: "corporate_finance_ib",
        label: "Corporate Finance & Investment Banking",
        group: "Finance, Accounting & Legal",
        keywords: ["investment banker", "corporate finance", "m&a analyst", "ib analyst"],
        skills: [
            "Valuation Modeling (DCF/Comps)",
            "M&A Analysis",
            "Capital Raising/Structuring",
            "Financial Statement Analysis",
            "Pitch Book Creation",
            "Due Diligence",
            "LBO Modeling",
            "Market Research",
            "Deal Structuring",
            "Client/Investor Relations",
        ],
    },
    {
        id: "accounting_bookkeeping",
        label: "Accounting & Bookkeeping",
        group: "Finance, Accounting & Legal",
        keywords: ["accountant", "bookkeeper", "accounts payable", "accounts receivable"],
        skills: [
            "General Ledger Management",
            "Accounts Payable/Receivable",
            "Financial Statement Preparation",
            "Reconciliations",
            "Accounting Software (QuickBooks/Xero/Sage)",
            "GAAP/IFRS Compliance",
            "Month-End/Year-End Close",
            "Payroll Processing",
            "Tax Filing Support",
            "Audit Preparation",
        ],
    },
    {
        id: "tax_strategy_audit",
        label: "Tax Strategy & Audit",
        group: "Finance, Accounting & Legal",
        keywords: ["tax accountant", "tax advisor", "auditor", "tax consultant"],
        skills: [
            "Tax Compliance & Filing",
            "Tax Planning & Strategy",
            "Audit Procedures",
            "Regulatory Research (Local Tax Codes)",
            "Transfer Pricing Basics",
            "Internal Controls Testing",
            "Risk-Based Auditing",
            "Financial Statement Audit",
            "Tax Software Proficiency",
            "Client Advisory",
        ],
    },
    {
        id: "corporate_law_counsel",
        label: "Corporate Law & In-House Counsel",
        group: "Finance, Accounting & Legal",
        keywords: ["corporate lawyer", "in-house counsel", "general counsel", "legal counsel"],
        skills: [
            "Contract Drafting & Negotiation",
            "Corporate Governance",
            "Regulatory Compliance",
            "Mergers & Acquisitions Support",
            "Risk Management (Legal)",
            "Intellectual Property Basics",
            "Employment Law Advisory",
            "Dispute Resolution",
            "Legal Research",
            "Cross-Border Transaction Support",
        ],
    },
    {
        id: "paralegal_legal_support",
        label: "Paralegal & Legal Support",
        group: "Finance, Accounting & Legal",
        keywords: ["paralegal", "legal assistant", "legal secretary"],
        skills: [
            "Legal Document Drafting",
            "Legal Research",
            "Case File Management",
            "Court Filing Procedures",
            "Client Intake & Communication",
            "Discovery & Evidence Organization",
            "Contract Review Support",
            "Billing/Time Tracking",
            "Litigation Support",
            "Regulatory Filing Assistance",
        ],
    },

    /* ===================== HEALTHCARE, MEDICAL & LIFE SCIENCES ===================== */
    {
        id: "clinical_nursing",
        label: "Clinical Nursing (RN, LPN, NP)",
        group: "Healthcare & Life Sciences",
        keywords: ["registered nurse", "rn", "lpn", "nurse practitioner", "clinical nurse"],
        skills: [
            "Patient Assessment",
            "Medication Administration",
            "Electronic Health Records (EHR/EMR)",
            "Care Plan Development",
            "Clinical Documentation",
            "Vital Signs Monitoring",
            "Infection Control Protocols",
            "Patient/Family Education",
            "Emergency Response",
            "Interdisciplinary Team Coordination",
        ],
    },
    {
        id: "physicians_medical_specialists",
        label: "Physicians & Medical Specialists",
        group: "Healthcare & Life Sciences",
        keywords: ["physician", "doctor", "md", "medical specialist", "surgeon"],
        skills: [
            "Diagnosis & Clinical Decision-Making",
            "Patient History & Examination",
            "Treatment Planning",
            "Medical Procedure Competency",
            "EHR Documentation",
            "Pharmacology Knowledge",
            "Evidence-Based Medicine",
            "Patient Communication",
            "Specialty-Specific Certifications",
            "Continuing Medical Education",
        ],
    },
    {
        id: "medical_admin_billing_coding",
        label: "Medical Administration & Billing/Coding",
        group: "Healthcare & Life Sciences",
        keywords: ["medical biller", "medical coder", "health information", "icd-10", "cpt coding"],
        skills: [
            "ICD-10/CPT Coding",
            "Medical Billing Systems",
            "Insurance Claims Processing",
            "HIPAA Compliance",
            "EHR Systems",
            "Revenue Cycle Management",
            "Patient Scheduling",
            "Denial Management",
            "Medical Terminology",
            "Health Records Auditing",
        ],
    },
    {
        id: "pharmacy_pharmacology",
        label: "Pharmacy & Pharmacology",
        group: "Healthcare & Life Sciences",
        keywords: ["pharmacist", "pharmacy technician", "pharmacology"],
        skills: [
            "Prescription Verification & Dispensing",
            "Drug Interaction Checking",
            "Pharmaceutical Compounding",
            "Patient Counseling",
            "Inventory & Controlled Substance Management",
            "Pharmacy Software Systems",
            "Regulatory Compliance (FDA/Pharmacy Board)",
            "Dosage Calculations",
            "Clinical Pharmacology Knowledge",
            "Insurance/Pricing Processing",
        ],
    },
    {
        id: "biotech_lab_research",
        label: "Biotechnology & Laboratory Research",
        group: "Healthcare & Life Sciences",
        keywords: ["lab technician", "research scientist", "biotechnology", "molecular biologist", "bioinformatics"],
        skills: [
            "Laboratory Techniques (PCR/Electrophoresis)",
            "Data Analysis & Statistics",
            "Lab Equipment Operation",
            "Experimental Design",
            "Bioinformatics Tools",
            "Sample Preparation & Handling",
            "Lab Safety & Compliance (GLP)",
            "Scientific Documentation/Reporting",
            "Cell Culture Techniques",
            "Research Protocol Development",
        ],
    },
    {
        id: "healthcare_management_admin",
        label: "Healthcare Management & Administration",
        group: "Healthcare & Life Sciences",
        keywords: ["healthcare administrator", "hospital manager", "clinic manager", "healthcare operations"],
        skills: [
            "Healthcare Operations Management",
            "Regulatory Compliance (HIPAA/Joint Commission)",
            "Budgeting & Financial Management",
            "Staff Scheduling & Management",
            "Patient Experience Management",
            "Quality Improvement Initiatives",
            "Healthcare IT Systems",
            "Facility/Resource Management",
            "Insurance & Reimbursement Knowledge",
            "Strategic Planning (Healthcare)",
        ],
    },
    {
        id: "dentistry_dental_hygiene",
        label: "Dentistry & Dental Hygiene",
        group: "Healthcare & Life Sciences",
        keywords: ["dentist", "dental hygienist", "dental assistant"],
        skills: [
            "Clinical Dental Procedures",
            "Dental Radiography (X-rays)",
            "Periodontal Assessment",
            "Patient Education (Oral Hygiene)",
            "Sterilization & Infection Control",
            "Dental Charting/Records",
            "Restorative Procedures",
            "Dental Software Systems",
            "Anesthesia Administration",
            "Treatment Planning",
        ],
    },
    {
        id: "physical_therapy_rehab",
        label: "Physical Therapy & Rehabilitation",
        group: "Healthcare & Life Sciences",
        keywords: ["physical therapist", "physiotherapist", "rehabilitation specialist", "occupational therapist"],
        skills: [
            "Patient Assessment & Diagnosis",
            "Treatment Plan Development",
            "Manual Therapy Techniques",
            "Therapeutic Exercise Prescription",
            "Rehabilitation Equipment Use",
            "Progress Documentation",
            "Patient Education",
            "Pain Management Strategies",
            "Mobility & Gait Training",
            "Interdisciplinary Care Coordination",
        ],
    },
    {
        id: "veterinary_medicine",
        label: "Veterinary Medicine",
        group: "Healthcare & Life Sciences",
        keywords: ["veterinarian", "vet tech", "veterinary technician"],
        skills: [
            "Animal Diagnosis & Examination",
            "Surgical Procedures (Veterinary)",
            "Vaccination & Preventive Care",
            "Animal Handling & Restraint",
            "Veterinary Pharmacology",
            "Diagnostic Imaging (X-ray/Ultrasound)",
            "Client/Owner Communication",
            "Lab Sample Analysis",
            "Emergency/Critical Care",
            "Veterinary Records Management",
        ],
    },

    /* ===================== ENGINEERING & ARCHITECTURE (TRADITIONAL) ===================== */
    {
        id: "civil_structural_engineering",
        label: "Civil & Structural Engineering",
        group: "Engineering & Architecture",
        keywords: ["civil engineer", "structural engineer"],
        skills: [
            "Structural Analysis & Design",
            "AutoCAD/Revit/Civil 3D",
            "Building Codes & Standards",
            "Site Planning & Surveying",
            "Construction Materials Knowledge",
            "Load Calculations",
            "Project Cost Estimation",
            "Geotechnical Considerations",
            "Construction Drawings & Specs",
            "Regulatory Permit Compliance",
        ],
    },
    {
        id: "mechanical_engineering",
        label: "Mechanical Engineering",
        group: "Engineering & Architecture",
        keywords: ["mechanical engineer", "mech eng"],
        skills: [
            "CAD Design (SolidWorks/AutoCAD)",
            "Thermodynamics & Fluid Mechanics",
            "Finite Element Analysis (FEA)",
            "Manufacturing Processes",
            "Mechanical Systems Design",
            "Materials Selection",
            "Prototyping & Testing",
            "GD&T (Tolerancing)",
            "Project/Product Lifecycle Management",
            "Technical Documentation",
        ],
    },
    {
        id: "electrical_engineering",
        label: "Electrical Engineering",
        group: "Engineering & Architecture",
        keywords: ["electrical engineer", "power systems engineer"],
        skills: [
            "Circuit Design & Analysis",
            "PCB Design",
            "Power Systems Engineering",
            "Embedded Systems (Arduino/ESP32)",
            "Control Systems",
            "Electrical Safety Standards",
            "SCADA/Automation",
            "Signal Processing",
            "CAD Tools (AutoCAD Electrical)",
            "Testing & Troubleshooting",
        ],
    },
    {
        id: "architecture_urban_planning",
        label: "Architecture & Urban Planning",
        group: "Engineering & Architecture",
        keywords: ["architect", "urban planner", "architectural designer"],
        skills: [
            "Architectural Design Principles",
            "Revit/AutoCAD/SketchUp",
            "Building Codes & Zoning",
            "Sustainable/Green Design",
            "Site Planning",
            "3D Modeling & Rendering",
            "Construction Documentation",
            "Project Coordination with Engineers",
            "Urban Planning Frameworks",
            "Client Presentation & Design Review",
        ],
    },
    {
        id: "aerospace_engineering",
        label: "Aerospace & Aeronautical Engineering",
        group: "Engineering & Architecture",
        keywords: ["aerospace engineer", "aeronautical engineer", "propulsion engineer"],
        skills: [
            "Aerodynamics",
            "Propulsion Systems",
            "Structural Analysis (Aerospace)",
            "CAD/CFD Tools",
            "Flight Mechanics & Control",
            "Materials for Aerospace",
            "Systems Integration & Testing",
            "Avionics Fundamentals",
            "Regulatory Standards (FAA/Aviation Authority)",
            "Technical Documentation & Reporting",
        ],
    },
    {
        id: "chemical_process_engineering",
        label: "Chemical & Process Engineering",
        group: "Engineering & Architecture",
        keywords: ["chemical engineer", "process engineer"],
        skills: [
            "Process Design & Simulation",
            "Mass & Energy Balances",
            "Reactor Design",
            "Process Safety Management",
            "P&ID Interpretation",
            "Quality Control in Chemical Processes",
            "Plant Operations Optimization",
            "Environmental/Regulatory Compliance",
            "Equipment Sizing & Specification",
            "Troubleshooting Process Issues",
        ],
    },

    /* ===================== EDUCATION, TRAINING & ACADEMIA ===================== */
    {
        id: "k12_education",
        label: "K-12 Education & Teaching",
        group: "Education & Training",
        keywords: ["teacher", "k-12", "elementary teacher", "high school teacher"],
        skills: [
            "Curriculum Planning & Delivery",
            "Classroom Management",
            "Differentiated Instruction",
            "Student Assessment & Grading",
            "Lesson Plan Development",
            "Parent/Guardian Communication",
            "Educational Technology Tools",
            "Behavior Management",
            "Individualized Education Plans (IEP)",
            "Subject-Matter Expertise",
        ],
    },
    {
        id: "higher_education_faculty",
        label: "Higher Education & University Faculty",
        group: "Education & Training",
        keywords: ["professor", "lecturer", "university faculty", "academic"],
        skills: [
            "Course Design & Curriculum Development",
            "Lecturing & Seminar Facilitation",
            "Academic Research & Publication",
            "Grant Writing",
            "Student Mentorship & Advising",
            "Peer Review",
            "Grading & Assessment Design",
            "Subject-Matter Expertise",
            "Academic Committee Participation",
            "Conference Presentation",
        ],
    },
    {
        id: "instructional_design_edtech",
        label: "Instructional Design & EdTech",
        group: "Education & Training",
        keywords: ["instructional designer", "edtech specialist", "learning experience designer"],
        skills: [
            "Curriculum/Course Design",
            "Learning Management Systems (LMS)",
            "Adult Learning Theory",
            "E-Learning Authoring Tools (Articulate/Captivate)",
            "Needs Analysis & Assessment Design",
            "Multimedia Content Development",
            "Learning Analytics",
            "Storyboarding for Courses",
            "Accessibility in Learning Design",
            "Stakeholder Collaboration",
        ],
    },
    {
        id: "corporate_training_ld",
        label: "Corporate Training & L&D",
        group: "Education & Training",
        keywords: ["corporate trainer", "learning and development", "l&d specialist", "training manager"],
        skills: [
            "Training Needs Analysis",
            "Workshop/Program Facilitation",
            "Curriculum & Content Development",
            "LMS Administration",
            "Performance Measurement (Kirkpatrick Model)",
            "Onboarding Program Design",
            "Leadership Development Programs",
            "Stakeholder Needs Assessment",
            "E-Learning Development",
            "Coaching & Feedback Delivery",
        ],
    },

    /* ===================== HOSPITALITY, RETAIL & TRADES ===================== */
    {
        id: "hotel_management_hospitality",
        label: "Hotel Management & Hospitality",
        group: "Hospitality, Retail & Trades",
        keywords: ["hotel manager", "hospitality manager", "front office manager"],
        skills: [
            "Guest Relations Management",
            "Front Office/Reservation Systems",
            "Revenue Management",
            "Staff Scheduling & Training",
            "Hospitality Service Standards",
            "Budget & P&L Management",
            "Housekeeping Operations Oversight",
            "Event/Conference Coordination",
            "Quality Assurance & Guest Satisfaction",
            "Vendor & Supplier Management",
        ],
    },
    {
        id: "culinary_food_service",
        label: "Culinary Arts & Food Service Management",
        group: "Hospitality, Retail & Trades",
        keywords: ["chef", "culinary", "kitchen manager", "food service manager"],
        skills: [
            "Menu Planning & Development",
            "Food Safety & Sanitation (HACCP)",
            "Kitchen Operations Management",
            "Inventory & Cost Control",
            "Recipe Standardization",
            "Staff Supervision & Training",
            "Plating & Presentation",
            "Vendor/Supplier Relations",
            "Allergen Management",
            "Equipment Maintenance Knowledge",
        ],
    },
    {
        id: "retail_store_management",
        label: "Retail & Store Management",
        group: "Hospitality, Retail & Trades",
        keywords: ["retail manager", "store manager", "assistant store manager"],
        skills: [
            "Sales Floor Management",
            "Inventory & Stock Control",
            "Staff Scheduling & Training",
            "Visual Merchandising",
            "POS Systems",
            "Customer Service Excellence",
            "Loss Prevention",
            "Sales Target Management",
            "Store Budget & P&L",
            "Team Leadership & Motivation",
        ],
    },
    {
        id: "construction_management",
        label: "Construction Management & Contracting",
        group: "Hospitality, Retail & Trades",
        keywords: ["construction manager", "general contractor", "site supervisor"],
        skills: [
            "Project Scheduling (Gantt/Critical Path)",
            "Budget & Cost Estimation",
            "Site Safety Management (OSHA)",
            "Subcontractor Coordination",
            "Building Codes & Permits",
            "Blueprint/Drawing Interpretation",
            "Quality Control Inspection",
            "Procurement of Materials",
            "Risk Management (Construction)",
            "Client/Stakeholder Communication",
        ],
    },
    {
        id: "fleet_transport_management",
        label: "Fleet & Transport Management",
        group: "Hospitality, Retail & Trades",
        keywords: ["fleet manager", "transport manager", "logistics fleet coordinator"],
        skills: [
            "Fleet Maintenance Scheduling",
            "Route Optimization",
            "Driver Management & Compliance",
            "Fuel & Cost Management",
            "Vehicle Tracking/Telematics Systems",
            "Regulatory Compliance (DOT/Transport Law)",
            "Inventory of Spare Parts",
            "Fleet Budgeting",
            "Safety & Incident Reporting",
            "Vendor/Supplier Negotiation",
        ],
    },

    /* ===================== NEW: MANUFACTURING & SKILLED TRADES ===================== */
    {
        id: "manufacturing_industrial_engineering",
        label: "Manufacturing & Industrial Engineering",
        group: "Manufacturing & Trades",
        keywords: ["manufacturing engineer", "industrial engineer", "production engineer", "plant engineer"],
        skills: [
            "Process Improvement (Lean/Kaizen)",
            "Production Line Optimization",
            "Six Sigma Methodologies",
            "Plant Layout & Workflow Design",
            "Quality Control Systems",
            "ERP/MES Systems",
            "Root Cause Analysis",
            "Equipment & Tooling Knowledge",
            "Capacity Planning",
            "Safety & Compliance (OSHA)",
        ],
    },
    {
        id: "quality_control_six_sigma",
        label: "Quality Control & Six Sigma",
        group: "Manufacturing & Trades",
        keywords: ["quality control", "quality engineer", "six sigma", "quality assurance manager (manufacturing)"],
        skills: [
            "Six Sigma (Green/Black Belt)",
            "Statistical Process Control (SPC)",
            "Root Cause Analysis (RCA)",
            "ISO 9001 Compliance",
            "Inspection & Testing Procedures",
            "Corrective/Preventive Action (CAPA)",
            "Quality Management Systems (QMS)",
            "Failure Mode Analysis (FMEA)",
            "Audit Preparation",
            "Process Documentation",
        ],
    },
    {
        id: "electricians_skilled_trades",
        label: "Electricians & Skilled Trades",
        group: "Manufacturing & Trades",
        keywords: ["electrician", "skilled tradesperson", "industrial electrician"],
        skills: [
            "Electrical Wiring & Installation",
            "Circuit Troubleshooting",
            "Electrical Code Compliance",
            "Blueprint Reading",
            "Panel & Conduit Installation",
            "Safety Procedures (Lockout/Tagout)",
            "Motor & Control Systems",
            "Power Tools Proficiency",
            "Preventive Maintenance",
            "Permit & Inspection Knowledge",
        ],
    },
    {
        id: "plumbing_hvac",
        label: "Plumbing & HVAC",
        group: "Manufacturing & Trades",
        keywords: ["plumber", "hvac technician", "hvac installer"],
        skills: [
            "Pipefitting & Installation",
            "HVAC System Installation & Repair",
            "Refrigeration Systems",
            "Blueprint & Schematic Reading",
            "Plumbing Code Compliance",
            "Diagnostic Troubleshooting",
            "Preventive Maintenance Scheduling",
            "Soldering/Brazing",
            "Customer Service (Field Work)",
            "Tool & Equipment Operation",
        ],
    },
    {
        id: "automotive_technology_repair",
        label: "Automotive Technology & Repair",
        group: "Manufacturing & Trades",
        keywords: ["automotive technician", "mechanic", "auto repair", "vehicle technician"],
        skills: [
            "Engine Diagnostics & Repair",
            "Electrical Systems Diagnosis",
            "OBD/Diagnostic Tools",
            "Brake & Suspension Systems",
            "Preventive Maintenance",
            "Transmission Repair",
            "Manufacturer Service Manuals",
            "Customer Communication (Estimates)",
            "Tool & Equipment Proficiency",
            "Safety Compliance",
        ],
    },

    /* ===================== NEW: ENERGY, ENVIRONMENT & AGRICULTURE ===================== */
    {
        id: "energy_renewables_utilities",
        label: "Energy & Renewable/Utilities",
        group: "Energy & Environment",
        keywords: ["energy engineer", "renewable energy", "solar engineer", "utilities manager", "power plant"],
        skills: [
            "Renewable Energy Systems (Solar/Wind)",
            "Energy Auditing",
            "Grid/Power Systems Knowledge",
            "Regulatory & Permitting Compliance",
            "Energy Efficiency Analysis",
            "Project Management (Energy)",
            "SCADA/Monitoring Systems",
            "Sustainability Reporting",
            "Technical Feasibility Studies",
            "Equipment Maintenance & Safety",
        ],
    },
    {
        id: "environmental_science_sustainability",
        label: "Environmental Science & Sustainability",
        group: "Energy & Environment",
        keywords: ["environmental scientist", "sustainability manager", "esg analyst"],
        skills: [
            "Environmental Impact Assessment",
            "Sustainability Reporting (ESG)",
            "Regulatory Compliance (Environmental)",
            "Data Collection & Field Sampling",
            "GIS Mapping",
            "Climate/Carbon Footprint Analysis",
            "Waste & Resource Management",
            "Environmental Policy Knowledge",
            "Stakeholder Engagement",
            "Remediation Planning",
        ],
    },
    {
        id: "agriculture_agronomy",
        label: "Agriculture & Agronomy",
        group: "Energy & Environment",
        keywords: ["agronomist", "agricultural specialist", "farm manager", "agritech"],
        skills: [
            "Crop Management & Rotation",
            "Soil Science & Fertility Analysis",
            "Pest & Disease Management",
            "Precision Agriculture Technology",
            "Irrigation Systems Management",
            "Yield Forecasting",
            "Farm Equipment Operation",
            "Sustainable Farming Practices",
            "Supply Chain (Agro-Commodities)",
            "Regulatory/Quality Standards (Agriculture)",
        ],
    },

    /* ===================== NEW: FINANCE EXTENSIONS ===================== */
    {
        id: "insurance_underwriting",
        label: "Insurance & Underwriting",
        group: "Insurance & Risk",
        keywords: ["underwriter", "insurance agent", "claims adjuster", "insurance analyst"],
        skills: [
            "Risk Assessment & Underwriting",
            "Policy Issuance & Review",
            "Claims Processing & Investigation",
            "Insurance Regulatory Compliance",
            "Actuarial Data Interpretation",
            "Client/Broker Relationship Management",
            "Premium Calculation",
            "Reinsurance Basics",
            "Fraud Detection",
            "Insurance Software Systems",
        ],
    },
    {
        id: "investment_wealth_management",
        label: "Investment & Wealth Management",
        group: "Insurance & Risk",
        keywords: ["wealth manager", "investment advisor", "portfolio manager", "financial advisor"],
        skills: [
            "Portfolio Management",
            "Asset Allocation Strategy",
            "Client Financial Planning",
            "Investment Research & Analysis",
            "Risk Tolerance Assessment",
            "Retirement & Estate Planning",
            "Regulatory Compliance (Investment)",
            "Market Analysis",
            "Client Relationship Management",
            "Performance Reporting",
        ],
    },
    {
        id: "actuarial_science",
        label: "Actuarial Science",
        group: "Insurance & Risk",
        keywords: ["actuary", "actuarial analyst"],
        skills: [
            "Statistical & Probability Modeling",
            "Risk & Reserve Calculation",
            "Actuarial Software (Prophet/AXIS)",
            "Life/Health/P&C Actuarial Methods",
            "Regulatory Reporting (Solvency)",
            "Pricing Model Development",
            "Data Analysis (SQL/R/Python)",
            "Mortality/Morbidity Analysis",
            "Exam Progress (SOA/IFoA)",
            "Financial Forecasting",
        ],
    },

    /* ===================== NEW: MEDIA, JOURNALISM & LANGUAGE ===================== */
    {
        id: "journalism_editorial",
        label: "Journalism & Editorial",
        group: "Media & Communications",
        keywords: ["journalist", "editor", "reporter", "editorial"],
        skills: [
            "News Writing & Reporting",
            "Investigative Research",
            "Editing & Proofreading",
            "Source Verification & Fact-Checking",
            "Interviewing Techniques",
            "AP Style/Editorial Standards",
            "Multimedia Storytelling",
            "Deadline Management",
            "Ethics in Journalism",
            "SEO for News Content",
        ],
    },
    {
        id: "broadcasting_media_production",
        label: "Broadcasting & Media Production",
        group: "Media & Communications",
        keywords: ["video producer", "broadcast technician", "media producer", "tv producer"],
        skills: [
            "Video Production & Editing",
            "Camera Operation",
            "Audio Engineering/Mixing",
            "Broadcast Equipment Operation",
            "Script Writing for Media",
            "Post-Production Workflow",
            "Live Broadcast Coordination",
            "Lighting Setup",
            "Content Scheduling",
            "Media Asset Management",
        ],
    },
    {
        id: "translation_localization",
        label: "Translation & Localization",
        group: "Media & Communications",
        keywords: ["translator", "localization specialist", "interpreter"],
        skills: [
            "Bilingual/Multilingual Fluency",
            "Translation Accuracy & Nuance",
            "CAT Tools (Trados/MemoQ)",
            "Localization for Cultural Context",
            "Terminology Management",
            "Proofreading & Quality Assurance",
            "Subtitling/Transcription",
            "Interpretation (Simultaneous/Consecutive)",
            "Industry-Specific Terminology",
            "Deadline & Project Management",
        ],
    },
    {
        id: "library_information_science",
        label: "Library & Information Science",
        group: "Media & Communications",
        keywords: ["librarian", "information specialist", "archivist"],
        skills: [
            "Cataloging & Classification",
            "Information Retrieval Systems",
            "Reference Services",
            "Digital Archiving",
            "Database/Metadata Management",
            "Research Assistance",
            "Collection Development",
            "Library Software Systems",
            "Information Literacy Instruction",
            "Records Management",
        ],
    },

    /* ===================== NEW: PUBLIC SECTOR & SOCIAL SERVICES ===================== */
    {
        id: "nonprofit_ngo_management",
        label: "Nonprofit & NGO Management",
        group: "Public Sector & Social Services",
        keywords: ["nonprofit manager", "ngo program manager", "program director"],
        skills: [
            "Grant Writing & Fundraising",
            "Program Design & Evaluation",
            "Donor Relationship Management",
            "Budget & Financial Stewardship",
            "Stakeholder/Community Engagement",
            "Monitoring & Evaluation (M&E)",
            "Volunteer Coordination",
            "Compliance with Donor Requirements",
            "Impact Reporting",
            "Partnership Development",
        ],
    },
    {
        id: "government_public_administration",
        label: "Government & Public Administration",
        group: "Public Sector & Social Services",
        keywords: ["public administrator", "government official", "civil servant", "policy officer"],
        skills: [
            "Public Policy Analysis",
            "Government Budgeting & Finance",
            "Regulatory Implementation",
            "Stakeholder/Community Consultation",
            "Program Administration",
            "Public Records Management",
            "Legislative Process Knowledge",
            "Intergovernmental Coordination",
            "Public Procurement",
            "Constituent Services",
        ],
    },
    {
        id: "urban_regional_planning_policy",
        label: "Urban & Regional Planning (Policy)",
        group: "Public Sector & Social Services",
        keywords: ["urban planner (policy)", "regional planner", "land use planner"],
        skills: [
            "Land Use Planning",
            "Zoning Regulation Analysis",
            "GIS Mapping & Spatial Analysis",
            "Public Consultation Facilitation",
            "Environmental Impact Review",
            "Transportation Planning",
            "Comprehensive Plan Development",
            "Policy Drafting",
            "Community Development Strategy",
            "Regulatory Compliance (Planning Law)",
        ],
    },
    {
        id: "psychology_counseling",
        label: "Psychology & Counseling",
        group: "Public Sector & Social Services",
        keywords: ["psychologist", "counselor", "therapist", "mental health counselor"],
        skills: [
            "Clinical Assessment & Diagnosis",
            "Therapeutic Techniques (CBT/etc.)",
            "Treatment Plan Development",
            "Crisis Intervention",
            "Case Documentation & Notes",
            "Ethical & Confidentiality Standards",
            "Client Rapport Building",
            "Group/Individual Therapy Facilitation",
            "Psychological Testing",
            "Referral Coordination",
        ],
    },
    {
        id: "social_work",
        label: "Social Work",
        group: "Public Sector & Social Services",
        keywords: ["social worker", "case manager", "child welfare"],
        skills: [
            "Case Management",
            "Client Needs Assessment",
            "Crisis Intervention",
            "Resource & Referral Coordination",
            "Documentation & Case Notes",
            "Family/Community Engagement",
            "Child/Adult Protection Protocols",
            "Advocacy",
            "Cultural Competency",
            "Interagency Collaboration",
        ],
    },
    {
        id: "funeral_services_mortuary",
        label: "Funeral Services & Mortuary",
        group: "Public Sector & Social Services",
        keywords: ["funeral director", "mortician", "embalmer"],
        skills: [
            "Embalming & Body Preparation",
            "Funeral Service Coordination",
            "Family Grief Support & Communication",
            "Regulatory Compliance (Health/Burial Law)",
            "Funeral Arrangement Planning",
            "Documentation & Permits",
            "Vendor Coordination (Caskets/Flowers)",
            "Facility & Equipment Maintenance",
            "Cultural/Religious Sensitivity",
            "Record Keeping",
        ],
    },
    {
        id: "security_law_enforcement",
        label: "Security & Law Enforcement",
        group: "Public Sector & Social Services",
        keywords: ["security officer", "police officer", "law enforcement", "security manager"],
        skills: [
            "Patrol & Surveillance Procedures",
            "Incident Reporting & Documentation",
            "Conflict De-escalation",
            "Emergency Response Protocols",
            "Access Control & Risk Assessment",
            "Investigation Techniques",
            "Use-of-Force Policy Knowledge",
            "Surveillance Systems (CCTV)",
            "Legal/Regulatory Knowledge",
            "Community/Public Relations",
        ],
    },

    /* ===================== NEW: TRANSPORT, AVIATION & MARITIME ===================== */
    {
        id: "aviation_flight_operations",
        label: "Aviation & Flight Operations",
        group: "Transport & Logistics",
        keywords: ["pilot", "flight crew", "aviation operations", "air traffic"],
        skills: [
            "Flight Planning & Navigation",
            "Aircraft Systems Knowledge",
            "Regulatory Compliance (FAA/ICAO)",
            "Crew Resource Management",
            "Emergency Procedures",
            "Weather Interpretation",
            "Flight Documentation/Logs",
            "Communication (ATC Protocols)",
            "Safety Management Systems",
            "Aircraft Pre-Flight Inspection",
        ],
    },
    {
        id: "maritime_shipping_operations",
        label: "Maritime & Shipping Operations",
        group: "Transport & Logistics",
        keywords: ["maritime officer", "shipping operations", "vessel operations", "marine logistics"],
        skills: [
            "Vessel Navigation & Operations",
            "Maritime Safety Regulations (SOLAS)",
            "Cargo Handling & Stowage",
            "Port Operations Coordination",
            "Shipping Documentation (Bill of Lading)",
            "Marine Engineering Basics",
            "Logistics & Freight Coordination",
            "Customs/Regulatory Compliance",
            "Crew Management",
            "Emergency Response (Maritime)",
        ],
    },
    {
        id: "telecommunications_engineering",
        label: "Telecommunications Engineering",
        group: "Transport & Logistics",
        keywords: ["telecom engineer", "telecommunications", "rf engineer", "network telecom"],
        skills: [
            "RF/Wireless Network Design",
            "Telecom Infrastructure (4G/5G)",
            "Fiber Optic Systems",
            "Network Protocols",
            "Telecom Equipment Installation",
            "Signal Testing & Optimization",
            "Regulatory/Spectrum Compliance",
            "VoIP Systems",
            "Telecom Project Management",
            "Troubleshooting & Maintenance",
        ],
    },

    /* ===================== NEW: FASHION & LIFESTYLE ===================== */
    {
        id: "fashion_design_merchandising",
        label: "Fashion Design & Merchandising",
        group: "Lifestyle & Personal Services",
        keywords: ["fashion designer", "merchandiser", "fashion buyer"],
        skills: [
            "Garment Design & Sketching",
            "Pattern Making & Draping",
            "Textile/Fabric Knowledge",
            "Trend Forecasting",
            "Merchandising & Buying Strategy",
            "CAD for Fashion (Illustrator/CLO3D)",
            "Production & Sourcing Coordination",
            "Collection Development",
            "Retail Visual Merchandising",
            "Brand & Market Positioning",
        ],
    },
    {
        id: "fitness_coaching_personal_training",
        label: "Fitness, Coaching & Personal Training",
        group: "Lifestyle & Personal Services",
        keywords: ["personal trainer", "fitness coach", "strength coach"],
        skills: [
            "Exercise Program Design",
            "Client Fitness Assessment",
            "Nutrition Basics & Guidance",
            "Injury Prevention & Modification",
            "Strength & Conditioning Techniques",
            "Motivational Coaching",
            "Group Fitness Instruction",
            "Progress Tracking & Goal Setting",
            "Equipment & Facility Safety",
            "Certification Maintenance (CPT/ACE/NASM)",
        ],
    },
];

/* ------------------------------------------------------------------ */
/* JIT TAXONOMY ROUTER                                                */
/* ------------------------------------------------------------------ */

/**
 * Builds a quick lookup index once at module load time so the router
 * doesn't re-scan the full array on every request.
 */
const TAXONOMY_INDEX: { category: TaxonomyCategory; keyword: string }[] = [];
for (const category of SKILL_TAXONOMY) {
    for (const keyword of category.keywords) {
        TAXONOMY_INDEX.push({ category, keyword: keyword.toLowerCase() });
    }
}

export interface RoutedTaxonomyResult {
    categories: TaxonomyCategory[];
    matchedBy: "keyword" | "fallback_generic";
}

/**
 * getRelevantTaxonomyCategories
 *
 * Fast, local, pre-LLM router. Given a job title and a list of
 * required skill strings, returns the 2-4 most relevant taxonomy
 * categories (NOT the AI prompt itself — this never touches the
 * model). The caller (ai-scoring.ts) is responsible for serializing
 * the returned skills into a compact prompt fragment.
 *
 * Matching strategy:
 *  1. Normalize jobTitle + requiredSkills into a single lowercase blob.
 *  2. Score every category by counting keyword hits in that blob.
 *  3. Return the top N categories by score (N = maxCategories).
 *  4. If nothing matches (score 0 everywhere), fall back to a small
 *     generic set so the AI still has *something* to anchor against
 *     rather than an empty taxonomy.
 *
 * @param jobTitle        e.g. "Senior Backend Engineer"
 * @param requiredSkills  e.g. ["Node.js", "PostgreSQL", "AWS"]
 * @param maxCategories   ceiling on how many categories to inject (default 3)
 */
export function getRelevantTaxonomyCategories(
    jobTitle: string,
    requiredSkills: string[] = [],
    maxCategories: number = 3
): RoutedTaxonomyResult {
    const blob = `${jobTitle} ${requiredSkills.join(" ")}`.toLowerCase();

    const scores = new Map<string, number>();
    for (const { category, keyword } of TAXONOMY_INDEX) {
        if (keyword && blob.includes(keyword)) {
            scores.set(category.id, (scores.get(category.id) ?? 0) + 1);
        }
    }

    if (scores.size === 0) {
        // Fallback: no keyword hit at all. Give the AI a small, broadly
        // applicable set rather than nothing. We deliberately keep this
        // tiny — it's a safety net, not a substitute for good keywords.
        const fallbackIds = [
            "operations_management_coo",
            "customer_support_ops",
            "executive_admin_assistance",
        ];
        return {
            categories: SKILL_TAXONOMY.filter((c) => fallbackIds.includes(c.id)),
            matchedBy: "fallback_generic",
        };
    }

    const ranked = Array.from(scores.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, maxCategories)
        .map(([id]) => id);

    return {
        categories: SKILL_TAXONOMY.filter((c) => ranked.includes(c.id)),
        matchedBy: "keyword",
    };
}

/**
 * serializeTaxonomyForPrompt
 *
 * Converts the routed categories (+ optional universal soft-skills
 * layer) into a compact text block for injection into the AI prompt.
 * This is what keeps token usage low — only ~100-200 words instead
 * of the full ~5,000-word taxonomy.
 *
 * @param categories          Output of getRelevantTaxonomyCategories().categories
 * @param includeSoftSkills   Whether to append the universal layer (default true)
 */
export function serializeTaxonomyForPrompt(
    categories: TaxonomyCategory[],
    includeSoftSkills: boolean = true
): string {
    const blocks = categories.map(
        (c) => `${c.label}:\n- ${c.skills.join("\n- ")}`
    );

    if (includeSoftSkills) {
        blocks.push(
            `${UNIVERSAL_SOFT_SKILLS.label}:\n- ${UNIVERSAL_SOFT_SKILLS.skills.join("\n- ")}`
        );
    }

    return blocks.join("\n\n");
}

/**
 * getCategoryById — convenience lookup, e.g. for admin UI / debugging.
 */
export function getCategoryById(id: string): TaxonomyCategory | undefined {
    return SKILL_TAXONOMY.find((c) => c.id === id);
}

/**
 * Sanity export — lets you assert SKILL_TAXONOMY.length === 100 in tests.
 */
export const TAXONOMY_CATEGORY_COUNT = SKILL_TAXONOMY.length;
