name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend image
      run: docker build ./backend --file backend/Dockerfile --tag optiohire-backend:$(date +%s)

    - name: Build Frontend image
      run: docker build ./frontend --file frontend/Dockerfile --tag optiohire-frontend:$(date +%s)
