name: Security Scans

on:
  push:
    branches: [ "main", "fearture/eml-tmpl" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1' # Weekly scan
  workflow_dispatch: # Lets you trigger this manually from the Actions tab

jobs:
  gitleaks-full-scan:
    name: Gitleaks Repo Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Force Gitleaks Repo Scan
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          ./gitleaks detect --source . -v

  trivy-full-fs-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,secret,config'
          severity: 'HIGH,CRITICAL'
          format: 'table'

  trivy-image-scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend image
        run: docker build ./backend --file backend/Dockerfile --tag optiohire-backend:latest

      - name: Build Frontend image
        run: docker build ./frontend --file frontend/Dockerfile --tag optiohire-frontend:latest

      - name: Run Trivy scan (Backend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'optiohire-backend:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy scan (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'optiohire-frontend:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
